### PR TITLE
Customs

### PR DESCRIPTION
**Pull request by sachinvas**
- Handle Posting Custom Items and CustomInfo's.

### CODE REVIEW

**Comment by welbesw** [comment]
@sachinvas thanks for the PR.  I've just updated the solution... can you take a look at the conflicts and then I can take a look at this PR again?  Thanks.

**Comment by sachinvas** [comment]
@welbesw, I have resolved the conflicts. Please review the branch and let me know, thanks.

**Comment by welbesw** [comment]
@sachinvas looks like there's a build error in the example project with the reference to postShipment now taking customsInfo.  Would probably make sense to overload the operator without the customs info object to not break backward compatibility with the API callers.

**Comment by sachinvas** [comment]
@welbesw, I have overloaded the `postShipment` method. Please review and let me know.

**Comment by TomWFox** [comment]
@sachinvas maybe you could add an example of adding customs info in the README?

**Pull request merged**
